# Generated by Django 2.1.7 on 2019-04-11 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior')], default='Freshman', max_length=9)),
                ('topic', models.CharField(choices=[('Ratios, Proportions and Percents', 'Ratios, Proportions and Percents'), ('Number Theory and Divisibility', 'Number Theory and Divisibility'), ('Counting Basics and Probability', 'Counting Basics and Probability'), ('Quadratics', 'Quadratics'), ('Probability', 'Probability'), ('Advanced Geometrical Concepts', 'Advanced Geometrical Concepts'), ('Perimeter, Area and Surface Area', 'Perimeter, Area and Surface Area'), ('Logic, Sets and Venn Diagram', 'Logic, Sets and Venn Diagram'), ('Similarity', 'Similarity'), ('Coordiante Geometry', 'Coordiante Geometry'), ('Circles', 'Circles'), ('Trigonometry', 'Trigonometry'), ('Parametric Equations', 'Parametric Equations'), ('Theory of Equations', 'Theory of Equations')], default='Ratios, Proportions and Percents', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('answer', models.CharField(default='1', max_length=250)),
                ('questionPicture', models.FileField(upload_to='')),
                ('answerPicture', models.FileField(upload_to='')),
                ('difficulty', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=3)),
                ('year', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
