# Generated by Django 2.1.7 on 2019-04-12 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('Ratios, Proportions and Percents', 'Ratios, Proportions and Percents'), ('Number Theory and Divisibility', 'Number Theory and Divisibility'), ('Counting Basics and Probability', 'Counting Basics and Probability'), ('Quadratics', 'Quadratics'), ('Probability', 'Probability'), ('Advanced Geometrical Concepts', 'Advanced Geometrical Concepts'), ('Perimeter, Area and Surface Area', 'Perimeter, Area and Surface Area'), ('Logic, Sets and Venn Diagram', 'Logic, Sets and Venn Diagram'), ('Similarity', 'Similarity'), ('Coordinate Geometry', 'Coordinate Geometry'), ('Circles', 'Circles'), ('Trigonometry', 'Trigonometry'), ('Parametric Equations', 'Parametric Equations'), ('Theory of Equations', 'Theory of Equations')], default='Ratios, Proportions and Percents', max_length=100),
        ),
    ]
