# Generated by Django 2.1.7 on 2019-04-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190411_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='progress2',
            field=models.CharField(default='}', max_length=1000),
        ),
    ]
