# Generated by Django 2.1.7 on 2019-04-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_progress2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='progress2',
            field=models.CharField(default='{"Ratios, Proportions and Percents": 0,"Number Theory and Divisibility": 0,"Counting Basics and Probability": 0,"Quadratics": 0,"Probability": 0,"Advanced Geometrical Concepts": 0,"Perimeter, Area and Surface Area": 0,"Logic, Sets and Venn Diagram": 0,"Similarity": 0,"Coordinate Geometry": 0,"Circles": 0,"Trigonometry": 0,"Parametric Equations": 0,"Theory of Equations": 0}', max_length=1000),
        ),
    ]
