# Generated by Django 2.1.7 on 2019-05-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190423_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='attempts',
            field=models.CharField(default='{"Ratios, Proportions and Percents": 3,"Number Theory and Divisibility": 3,"Counting Basics and Probability": 3,"Quadratics": 3,"Probability": 3,"Advanced Geometrical Concepts": 3,"Perimeter, Area and Surface Area": 3,"Logic, Sets and Venn Diagram": 3,"Similarity": 3,"Coordinate Geometry": 3,"Circles": 3,"Trigonometry": 3,"Parametric Equations": 3,"Theory of Equations": 3}', max_length=1000),
        ),
    ]
