# Generated by Django 2.1.7 on 2019-05-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_currquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currQuestions',
            field=models.CharField(default='{"Ratios, Proportions and Percents": "N","Number Theory and Divisibility": "N","Counting Basics and Probability": "N","Quadratics": "N","Probability": "N","Advanced Geometrical Concepts": "N","Perimeter, Area and Surface Area": "N","Logic, Sets and Venn Diagram": "N","Similarity": "N","Coordinate Geometry": "N","Circles": "N","Trigonometry": "N","Parametric Equations": "N","Theory of Equations": "N"}', max_length=1000),
        ),
    ]
