# Generated by Django 2.1.7 on 2019-05-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190430_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currCorrect',
            field=models.CharField(default='{"Ratios, Proportions and Percents": False,"Number Theory and Divisibility": False,"Counting Basics and Probability": False,"Quadratics": False,"Probability": False,"Advanced Geometrical Concepts": False,"Perimeter, Area and Surface Area": False,"Logic, Sets and Venn Diagram": False,"Similarity": False,"Coordinate Geometry": False,"Circles": False,"Trigonometry": False,"Parametric Equations": False,"Theory of Equations": False}', max_length=1000),
        ),
    ]
