# Generated by Django 2.1.7 on 2019-05-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190505_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('Ratios, Proportions and Percents', 'Ratios, Proportions and Percents'), ('Number Theory and Divisibility', 'Number Theory and Divisibility'), ('Counting Basics and Probability', 'Counting Basics and Probability'), ('Quadratics', 'Quadratics'), ('Probability', 'Probability'), ('Advanced Geometrical Concepts', 'Advanced Geometrical Concepts'), ('Perimeter, Area and Surface Area', 'Perimeter, Area and Surface Area'), ('Logic, Sets and Venn Diagram', 'Logic, Sets and Venn Diagram'), ('Similarity', 'Similarity'), ('Coordinate Geometry', 'Coordinate Geometry'), ('Circles', 'Circles'), ('Trigonometry', 'Trigonometry'), ('Parametric Equations', 'Parametric Equations'), ('Theory of Equations', 'Theory of Equations'), ('Freshman Regionals', 'Freshman Regionals'), ('Freshman State', 'Freshman State'), ('Sophomore Regionals', 'Sophomore Regionals'), ('Sophomore State', 'Sophomore State'), ('Junior Regionals', 'Junior Regionals'), ('Junior State', 'Junior State'), ('Senior Regionals', 'Senior Regionals'), ('Senior State', 'Senior State')], default='Ratios, Proportions and Percents', max_length=100),
        ),
    ]
