# Generated by Django 2.1.7 on 2019-05-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_topic_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='attempts',
            field=models.CharField(default='{"Ratios, Proportions and Percents": 3,"Number Theory and Divisibility": 3,"Counting Basics and Probability": 3,"Quadratics": 3,"Freshman Conference": 3,"Probability": 3,"Advanced Geometrical Concepts": 3,"Perimeter, Area and Surface Area": 3,"Logic, Sets and Venn Diagram": 3,"Similarity": 3,"Coordinate Geometry": 3,"Circles": 3,"Sophomore Conference": 3,"Trigonometry": 3,"Junior Conference": 3,"Parametric Equations": 3,"Theory of Equations": 3,"Senior Conference": 3,"Freshman Regionals": 3,"Freshman State": 3,"Sophomore Regionals": 3,"Sophomore State": 3,"Junior Regionals": 3,"Junior State": 3,"Senior Regionals": 3,"Senior State": 3}', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='currCorrect',
            field=models.CharField(default='{"Ratios, Proportions and Percents": "F","Number Theory and Divisibility": "F","Counting Basics and Probability": "F","Quadratics": "F","Freshman Conference": "F","Probability": "F","Advanced Geometrical Concepts": "F","Perimeter, Area and Surface Area": "F","Logic, Sets and Venn Diagram": "F","Similarity": "F","Coordinate Geometry": "F","Circles": "F","Sophomore Conference": "F","Trigonometry": "F","Junior Conference": "F","Parametric Equations": "F","Theory of Equations": "F","Senior Conference": "F","Freshman Regionals": "F","Freshman State": "F","Sophomore Regionals": "F","Sophomore State": "F","Junior Regionals": "F","Junior State": "F","Senior Regionals": "F","Senior State": "F"}', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='currQuestions',
            field=models.CharField(default='{"Ratios, Proportions and Percents": "N","Number Theory and Divisibility": "N","Counting Basics and Probability": "N","Quadratics": "N","Freshman Conference": "N","Probability": "N","Advanced Geometrical Concepts": "N","Perimeter, Area and Surface Area": "N","Logic, Sets and Venn Diagram": "N","Similarity": "N","Coordinate Geometry": "N","Circles": "N","Sophomore Conference": "N","Trigonometry": "N","Junior Conference": "N","Parametric Equations": "N","Theory of Equations": "N","Senior Conference": "N","Freshman Regionals": "N","Freshman State": "N","Sophomore Regionals": "N","Sophomore State": "N","Junior Regionals": "N","Junior State": "N","Senior Regionals": "N","Senior State": "N"}', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='progress2',
            field=models.CharField(default='{"Ratios, Proportions and Percents": 0,"Number Theory and Divisibility": 0,"Counting Basics and Probability": 0,"Quadratics": 0,"Freshman Conference": 0,"Probability": 0,"Advanced Geometrical Concepts": 0,"Perimeter, Area and Surface Area": 0,"Logic, Sets and Venn Diagram": 0,"Similarity": 0,"Coordinate Geometry": 0,"Circles": 0,"Sophomore Conference": 0,"Trigonometry": 0,"Junior Conference": 0,"Parametric Equations": 0,"Theory of Equations": 0,"Senior Conference": 0,"Freshman Regionals": 0,"Freshman State": 0,"Sophomore Regionals": 0,"Sophomore State": 0,"Junior Regionals": 0,"Junior State": 0,"Senior Regionals": 0,"Senior State": 0}', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='topicOrder',
            field=models.CharField(default='{"Ratios, Proportions and Percents": 0,"Number Theory and Divisibility": 1,"Counting Basics and Probability": 2,"Quadratics": 3,"Freshman Conference": 4,"Probability": 5,"Advanced Geometrical Concepts": 6,"Perimeter, Area and Surface Area": 7,"Logic, Sets and Venn Diagram": 8,"Similarity": 9,"Coordinate Geometry": 10,"Circles": 11,"Sophomore Conference": 12,"Trigonometry": 13,"Junior Conference": 14,"Parametric Equations": 15,"Theory of Equations": 16,"Senior Conference": 17,"Freshman Regionals": 18,"Freshman State": 19,"Sophomore Regionals": 20,"Sophomore State": 21,"Junior Regionals": 22,"Junior State": 23,"Senior Regionals": 24,"Senior State": 25}', max_length=1000),
        ),
    ]
