# Generated by Django 2.1.7 on 2019-06-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190519_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='firstFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='topic',
            name='secondFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='topic',
            name='thirdFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
