# Generated by Django 2.1.7 on 2019-06-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190606_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='fourthDescription',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='secondDescription',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='thirdDescription',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
