# Generated by Django 2.1.7 on 2019-06-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190606_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answerText',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='questionText',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answerPicture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionPicture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
