# Generated by Django 2.1.7 on 2019-06-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190612_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='testTime',
            field=models.CharField(default='{"2016 Advanced Geometrical Concepts": 0,"2016 Ratios, Proportions and Percents": 0,"RAND Ratios, Proportions and Percents": 0}', max_length=99999999999),
        ),
    ]
