# Generated by Django 2.1.7 on 2019-06-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_profile_testtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='testAnswers',
            field=models.CharField(default='{"2016 Advanced Geometrical Concepts": [, , , , ],"2016 Ratios, Proportions and Percents": [, , , , ],"RAND Ratios, Proportions and Percents": [, , , , ]}', max_length=999),
        ),
    ]
