# Generated by Django 2.1.7 on 2019-06-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_profile_testanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='testAnswers',
            field=models.CharField(default='{"2016 Advanced Geometrical Concepts": ["", "", "", "", ""],"2016 Ratios, Proportions and Percents": ["", "", "", "", ""],"RAND Ratios, Proportions and Percents": ["", "", "", "", ""]}', max_length=999),
        ),
    ]
