# Generated by Django 2.1.7 on 2019-06-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20190619_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='testDistribution',
            field=models.CharField(default='{"2016 Advanced Geometrical Concepts": [0, 0, 0, 0, 0],"2016 Ratios, Proportions and Percents": [0, 0, 0, 0, 0],"RAND Ratios, Proportions and Percents": [0, 0, 0, 0, 0]}', max_length=999),
        ),
    ]
