# Generated by Django 2.1.7 on 2019-06-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190622_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('Ratios, Proportions and Percents', 'Ratios, Proportions and Percents'), ('Number Theory and Divisibility', 'Number Theory and Divisibility'), ('Counting Basics and Probability', 'Counting Basics and Probability'), ('Number Bases', 'Number Bases'), ('Quadratics', 'Quadratics'), ('Probability', 'Probability'), ('Functions', 'Functions'), ('Advanced Geometrical Concepts', 'Advanced Geometrical Concepts'), ('Perimeter, Area and Surface Area', 'Perimeter, Area and Surface Area'), ('Logic, Sets and Venn Diagram', 'Logic, Sets and Venn Diagram'), ('Geometric Probability', 'Geometric Probability'), ('Similarity', 'Similarity'), ('Coordinate Geometry', 'Coordinate Geometry'), ('Circles', 'Circles'), ('Trigonometry', 'Trigonometry'), ('Polynomials', 'Polynomials'), ('Logs and Exponents', 'Logs and Exponents'), ('Transformations using Matrices', 'Transformations using Matrices'), ('Parametric Equations', 'Parametric Equations'), ('Theory of Equations', 'Theory of Equations'), ('Sequences and Series', 'Sequences and Series'), ('Vectors', 'Vectors'), ('Freshman Regionals', 'Freshman Regionals'), ('Freshman State', 'Freshman State'), ('Sophomore Regionals', 'Sophomore Regionals'), ('Sophomore State', 'Sophomore State'), ('Junior Regionals', 'Junior Regionals'), ('Junior State', 'Junior State'), ('Senior Regionals', 'Senior Regionals'), ('Senior State', 'Senior State')], default='Ratios, Proportions and Percents', max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(choices=[('Ratios, Proportions and Percents', 'Ratios, Proportions and Percents'), ('Number Theory and Divisibility', 'Number Theory and Divisibility'), ('Counting Basics and Probability', 'Counting Basics and Probability'), ('Number Bases', 'Number Bases'), ('Quadratics', 'Quadratics'), ('Probability', 'Probability'), ('Functions', 'Functions'), ('Advanced Geometrical Concepts', 'Advanced Geometrical Concepts'), ('Perimeter, Area and Surface Area', 'Perimeter, Area and Surface Area'), ('Logic, Sets and Venn Diagram', 'Logic, Sets and Venn Diagram'), ('Geometric Probability', 'Geometric Probability'), ('Similarity', 'Similarity'), ('Coordinate Geometry', 'Coordinate Geometry'), ('Circles', 'Circles'), ('Trigonometry', 'Trigonometry'), ('Polynomials', 'Polynomials'), ('Logs and Exponents', 'Logs and Exponents'), ('Transformations using Matrices', 'Transformations using Matrices'), ('Parametric Equations', 'Parametric Equations'), ('Theory of Equations', 'Theory of Equations'), ('Sequences and Series', 'Sequences and Series'), ('Vectors', 'Vectors'), ('Freshman Regionals', 'Freshman Regionals'), ('Freshman State', 'Freshman State'), ('Sophomore Regionals', 'Sophomore Regionals'), ('Sophomore State', 'Sophomore State'), ('Junior Regionals', 'Junior Regionals'), ('Junior State', 'Junior State'), ('Senior Regionals', 'Senior Regionals'), ('Senior State', 'Senior State')], default='Ratios, Proportions and Percents', max_length=100),
        ),
    ]
