# Generated by Django 2.1.7 on 2019-08-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20190701_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='progress',
            field=models.CharField(default='{"Ratios, Proportions and Percents": [0],"Number Theory and Divisibility": [0],"Counting Basics and Probability": [0],"Number Bases": [0],"Quadratics": [0],"Freshman Conference": [0],"Probability": [0],"Functions": [0],"Advanced Geometrical Concepts": [0],"Perimeter, Area and Surface Area": [0],"Logic, Sets and Venn Diagram": [0],"Geometric Probability": [0],"Similarity": [0],"Coordinate Geometry": [0],"Circles": [0],"Sophomore Conference": [0],"Trigonometry": [0],"Polynomials": [0],"Logs and Exponents": [0],"Transformations using Matrices": [0],"Junior Conference": [0],"Parametric Equations": [0],"Theory of Equations": [0],"Sequences and Series": [0],"Vectors": [0],"Senior Conference": [0],"Freshman Regionals": [0],"Freshman State": [0],"Sophomore Regionals": [0],"Sophomore State": [0],"Junior Regionals": [0],"Junior State": [0],"Senior Regionals": [0],"Senior State": [0]}', max_length=999999),
        ),
    ]
